
name: Cloudflare Pages

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.18.1

      - name: Install and Build
        run: |
          pnpm install
          pnpm build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: fe8ac812a2141ac30b230d67ebaa28ad
          projectName: fostr
          directory: ./dist
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
